# Generated by Django 3.1.7 on 2021-03-26 19:56

import application.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Date of last update (wall or any widget)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wall',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Date of last update (wall or any widget)')),
                ('allow_anonymous_view', models.BooleanField(default=False, verbose_name='Allow anonymous view mode')),
                ('title', models.CharField(blank=True, default='Untitled', max_length=200, null=True, verbose_name='Wall title')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Wall description')),
                ('lock_widgets', models.BooleanField(default=False, verbose_name='Lock widgets custom actions')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Date of last update (wall or any widget)')),
                ('w', models.IntegerField(default=200, validators=[django.core.validators.MinValueValidator(50)], verbose_name='Widget width')),
                ('h', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(50)], verbose_name='Widget height')),
                ('z', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Widget z index(stack position)')),
                ('x', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Offset left from parent')),
                ('y', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Offset top from parent')),
                ('font_size', models.IntegerField(default=16, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(6)], verbose_name='Widget font size')),
                ('font_weight', models.IntegerField(default=400, validators=[django.core.validators.MaxValueValidator(900), django.core.validators.MinValueValidator(100)], verbose_name='Widget font weight')),
                ('background_color', models.CharField(default='#ffffff', max_length=9, validators=[application.models.concrete.general_declaration.ColorValidator])),
                ('text_color', models.CharField(default='#000000', max_length=9, validators=[application.models.concrete.general_declaration.ColorValidator])),
                ('border', models.BooleanField(default=True)),
                ('help', models.CharField(blank=True, max_length=200, null=True)),
                ('href', models.URLField(blank=True, null=True)),
                ('text', models.CharField(blank=True, max_length=2048, null=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.container')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SimpleText',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Date of last update (wall or any widget)')),
                ('w', models.IntegerField(default=200, validators=[django.core.validators.MinValueValidator(50)], verbose_name='Widget width')),
                ('h', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(50)], verbose_name='Widget height')),
                ('z', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Widget z index(stack position)')),
                ('x', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Offset left from parent')),
                ('y', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Offset top from parent')),
                ('font_size', models.IntegerField(default=16, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(6)], verbose_name='Widget font size')),
                ('font_weight', models.IntegerField(default=400, validators=[django.core.validators.MaxValueValidator(900), django.core.validators.MinValueValidator(100)], verbose_name='Widget font weight')),
                ('background_color', models.CharField(default='#ffffff', max_length=9, validators=[application.models.concrete.general_declaration.ColorValidator])),
                ('text_color', models.CharField(default='#000000', max_length=9, validators=[application.models.concrete.general_declaration.ColorValidator])),
                ('border', models.BooleanField(default=True)),
                ('help', models.CharField(blank=True, max_length=200, null=True)),
                ('text_content', models.TextField(blank=True, null=True, verbose_name='Text content of widget')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.container')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SimpleSwitch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Date of last update (wall or any widget)')),
                ('w', models.IntegerField(default=200, validators=[django.core.validators.MinValueValidator(50)], verbose_name='Widget width')),
                ('h', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(50)], verbose_name='Widget height')),
                ('z', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Widget z index(stack position)')),
                ('x', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Offset left from parent')),
                ('y', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Offset top from parent')),
                ('font_size', models.IntegerField(default=16, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(6)], verbose_name='Widget font size')),
                ('font_weight', models.IntegerField(default=400, validators=[django.core.validators.MaxValueValidator(900), django.core.validators.MinValueValidator(100)], verbose_name='Widget font weight')),
                ('background_color', models.CharField(default='#ffffff', max_length=9, validators=[application.models.concrete.general_declaration.ColorValidator])),
                ('text_color', models.CharField(default='#000000', max_length=9, validators=[application.models.concrete.general_declaration.ColorValidator])),
                ('border', models.BooleanField(default=True)),
                ('help', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('value', models.BooleanField(default=False)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.container')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SimpleList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Date of last update (wall or any widget)')),
                ('w', models.IntegerField(default=200, validators=[django.core.validators.MinValueValidator(50)], verbose_name='Widget width')),
                ('h', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(50)], verbose_name='Widget height')),
                ('z', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Widget z index(stack position)')),
                ('x', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Offset left from parent')),
                ('y', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Offset top from parent')),
                ('font_size', models.IntegerField(default=16, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(6)], verbose_name='Widget font size')),
                ('font_weight', models.IntegerField(default=400, validators=[django.core.validators.MaxValueValidator(900), django.core.validators.MinValueValidator(100)], verbose_name='Widget font weight')),
                ('background_color', models.CharField(default='#ffffff', max_length=9, validators=[application.models.concrete.general_declaration.ColorValidator])),
                ('text_color', models.CharField(default='#000000', max_length=9, validators=[application.models.concrete.general_declaration.ColorValidator])),
                ('border', models.BooleanField(default=True)),
                ('help', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('items', models.JSONField(default=list)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.container')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Date of last update (wall or any widget)')),
                ('w', models.IntegerField(default=200, validators=[django.core.validators.MinValueValidator(50)], verbose_name='Widget width')),
                ('h', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(50)], verbose_name='Widget height')),
                ('z', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Widget z index(stack position)')),
                ('x', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Offset left from parent')),
                ('y', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Offset top from parent')),
                ('font_size', models.IntegerField(default=16, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(6)], verbose_name='Widget font size')),
                ('font_weight', models.IntegerField(default=400, validators=[django.core.validators.MaxValueValidator(900), django.core.validators.MinValueValidator(100)], verbose_name='Widget font weight')),
                ('background_color', models.CharField(default='#ffffff', max_length=9, validators=[application.models.concrete.general_declaration.ColorValidator])),
                ('text_color', models.CharField(default='#000000', max_length=9, validators=[application.models.concrete.general_declaration.ColorValidator])),
                ('border', models.BooleanField(default=True)),
                ('help', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('value', models.BigIntegerField(default=0)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.container')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='container',
            name='wall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.wall'),
        ),
    ]
