# Generated by Django 3.1.5 on 2021-01-24 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wall',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Date of last update (wall or any widget)')),
                ('title', models.CharField(max_length=200, verbose_name='Wall title')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Wall description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SimpleTextWidget',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Date of last update (wall or any widget)')),
                ('text_content', models.TextField(max_length=2000, verbose_name='Text content of widget')),
                ('wall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.wall')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
