# Generated by Django 3.1.5 on 2021-02-01 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SimpleTextWidget',
        ),
        migrations.DeleteModel(
            name='Wall',
        ),
    ]
