# Generated by Django 3.1.5 on 2021-03-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20210327_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='w',
            field=models.IntegerField(default=2000, verbose_name='Container width'),
        ),
    ]
