# Generated by Django 3.1.5 on 2021-02-07 21:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0003_auto_20210207_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='wall',
            name='change_anonymous',
            field=models.BooleanField(default=False, verbose_name='Define if anonymous user may see data'),
        ),
        migrations.AddField(
            model_name='wall',
            name='change_users',
            field=models.ManyToManyField(related_name='change_wall', to=settings.AUTH_USER_MODEL, verbose_name='List of allowed users (change permission)'),
        ),
        migrations.AddField(
            model_name='wall',
            name='view_anonymous',
            field=models.BooleanField(default=False, verbose_name='Define if anonymous user may view data'),
        ),
        migrations.AddField(
            model_name='wall',
            name='view_users',
            field=models.ManyToManyField(related_name='view_wall', to=settings.AUTH_USER_MODEL, verbose_name='List of allowed users (view permission)'),
        ),
    ]
