# Generated by Django 3.1.5 on 2021-02-01 21:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_simpletextwidget_wall'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleText',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Date of last update (wall or any widget)')),
                ('width', models.IntegerField(default=200, validators=[django.core.validators.MinValueValidator(200), django.core.validators.MaxValueValidator(2000)], verbose_name='Widget width')),
                ('height', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(2000)], verbose_name='Widget height')),
                ('left', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Offset left from parent')),
                ('top', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Offset top from parent')),
                ('text_content', models.TextField(max_length=2000, verbose_name='Text content of widget')),
                ('font_color', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info'), ('white', 'White'), ('black', 'White')], default='black', max_length=10)),
                ('background_color', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info'), ('white', 'White'), ('black', 'White')], default='white', max_length=10)),
                ('wall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.wall')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='SimpleTextWidget',
        ),
    ]
