# Generated by Django 3.1.5 on 2021-04-10 12:44

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20210405_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='uid',
            field=hashid_field.field.HashidField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, null=True, prefix='container_'),
        ),
        migrations.AddField(
            model_name='counter',
            name='uid',
            field=hashid_field.field.HashidField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, null=True, prefix='counter_'),
        ),
        migrations.AddField(
            model_name='simplelist',
            name='uid',
            field=hashid_field.field.HashidField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, null=True, prefix='simple_list_'),
        ),
        migrations.AddField(
            model_name='simpleswitch',
            name='uid',
            field=hashid_field.field.HashidField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, null=True, prefix='simple_switch_'),
        ),
        migrations.AddField(
            model_name='simpletext',
            name='uid',
            field=hashid_field.field.HashidField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, null=True, prefix='simple_text_'),
        ),
        migrations.AddField(
            model_name='url',
            name='uid',
            field=hashid_field.field.HashidField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, null=True, prefix='url_'),
        ),
        migrations.AddField(
            model_name='wall',
            name='uid',
            field=hashid_field.field.HashidField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, null=True, prefix='wall_'),
        ),
    ]
