# Generated by Django 3.1.5 on 2021-02-07 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0005_auto_20210207_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wall',
            name='allowed_users',
            field=models.ManyToManyField(related_name='related_wall', to=settings.AUTH_USER_MODEL, verbose_name='List of allowed users'),
        ),
        migrations.AlterField(
            model_name='wall',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
