# Generated by Django 3.1.5 on 2021-02-07 21:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0006_auto_20210207_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wall',
            name='allowed_anonymous',
            field=models.BooleanField(default=False, verbose_name='Anonymous user may interact with data'),
        ),
        migrations.AlterField(
            model_name='wall',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_wall', to=settings.AUTH_USER_MODEL, verbose_name='List of allowed users'),
        ),
    ]
