# Generated by Django 3.1.5 on 2021-04-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20210410_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simplelist',
            name='description',
        ),
        migrations.AddField(
            model_name='simpletext',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='url',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='simplelist',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
