# Generated by Django 3.1.5 on 2021-04-10 13:10

from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20210410_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Date of last update (wall or any widget)')),
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('wall', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application.wall')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
