# Generated by Django 3.1.5 on 2021-02-13 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_delete_devuser1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wall',
            name='allowed_anonymous',
        ),
    ]
