# Generated by Django 3.1.5 on 2021-04-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_auto_20210410_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
