# Generated by Django 3.1.5 on 2021-02-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_remove_wall_allowed_anonymous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wall',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Wall description'),
        ),
        migrations.AlterField(
            model_name='wall',
            name='title',
            field=models.CharField(default='Untitled', max_length=200, verbose_name='Wall title'),
        ),
    ]
