# Generated by Django 3.1.5 on 2021-02-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_auto_20210213_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wall',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Wall description'),
        ),
    ]
