# Generated by Django 3.1.5 on 2021-04-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_port_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='vertical',
            field=models.BooleanField(default=True),
        ),
    ]
