# Generated by Django 3.1.5 on 2021-04-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_counter_vertical'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='step',
            field=models.IntegerField(default=1),
        ),
    ]
