# Generated by Django 3.1.5 on 2021-02-20 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_auto_20210219_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='z',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)], verbose_name='Widget z index(stack position)'),
        ),
        migrations.AlterField(
            model_name='richtext',
            name='z',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)], verbose_name='Widget z index(stack position)'),
        ),
        migrations.AlterField(
            model_name='simplelist',
            name='z',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)], verbose_name='Widget z index(stack position)'),
        ),
        migrations.AlterField(
            model_name='simpletext',
            name='z',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)], verbose_name='Widget z index(stack position)'),
        ),
        migrations.AlterField(
            model_name='url',
            name='z',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)], verbose_name='Widget z index(stack position)'),
        ),
    ]
