# Generated by Django 3.1.5 on 2021-02-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_auto_20210220_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='wall',
            name='w',
            field=models.IntegerField(default=1000, verbose_name='Wall width'),
        ),
    ]
