# Generated by Django 3.1.5 on 2021-02-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_wall_w'),
    ]

    operations = [
        migrations.AddField(
            model_name='wall',
            name='h',
            field=models.IntegerField(default=600, verbose_name='Wall height'),
        ),
    ]
