# Generated by Django 3.1.5 on 2021-04-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_auto_20210410_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplelist',
            name='inner_border',
            field=models.BooleanField(default=True, help_text='Set border for items in list'),
        ),
    ]
