# Generated by Django 3.1.5 on 2021-02-21 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_auto_20210220_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='x',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Offset left from parent'),
        ),
        migrations.AlterField(
            model_name='counter',
            name='y',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Offset top from parent'),
        ),
        migrations.AlterField(
            model_name='richtext',
            name='x',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Offset left from parent'),
        ),
        migrations.AlterField(
            model_name='richtext',
            name='y',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Offset top from parent'),
        ),
        migrations.AlterField(
            model_name='simplelist',
            name='x',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Offset left from parent'),
        ),
        migrations.AlterField(
            model_name='simplelist',
            name='y',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Offset top from parent'),
        ),
        migrations.AlterField(
            model_name='simpletext',
            name='x',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Offset left from parent'),
        ),
        migrations.AlterField(
            model_name='simpletext',
            name='y',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Offset top from parent'),
        ),
        migrations.AlterField(
            model_name='url',
            name='x',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Offset left from parent'),
        ),
        migrations.AlterField(
            model_name='url',
            name='y',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Offset top from parent'),
        ),
    ]
