# Generated by Django 3.1.5 on 2021-02-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_auto_20210221_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='border',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='richtext',
            name='border',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='simplelist',
            name='border',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='simpletext',
            name='border',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='url',
            name='border',
            field=models.BooleanField(default=True),
        ),
    ]
