# Generated by Django 3.1.5 on 2021-04-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_auto_20210411_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='sync_id',
            field=models.CharField(blank=True, help_text='Id of widget to sync with', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='simplelist',
            name='sync_id',
            field=models.CharField(blank=True, help_text='Id of widget to sync with', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='simpleswitch',
            name='sync_id',
            field=models.CharField(blank=True, help_text='Id of widget to sync with', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='simpletext',
            name='sync_id',
            field=models.CharField(blank=True, help_text='Id of widget to sync with', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='url',
            name='sync_id',
            field=models.CharField(blank=True, help_text='Id of widget to sync with', max_length=20, null=True),
        ),
    ]
