# Generated by Django 3.1.5 on 2021-02-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_auto_20210226_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpletext',
            name='text_content',
            field=models.TextField(blank=True, null=True, verbose_name='Text content of widget'),
        ),
    ]
