# Generated by Django 3.1.5 on 2021-04-11 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_auto_20210411_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='sync_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.counter'),
        ),
        migrations.AlterField(
            model_name='simplelist',
            name='sync_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.simplelist'),
        ),
        migrations.AlterField(
            model_name='simpleswitch',
            name='sync_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.simpleswitch'),
        ),
        migrations.AlterField(
            model_name='simpletext',
            name='sync_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.simpletext'),
        ),
        migrations.AlterField(
            model_name='url',
            name='sync_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.url'),
        ),
    ]
