# Generated by Django 3.1.5 on 2021-02-26 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0021_auto_20210226_2238'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RichText',
        ),
    ]
