# Generated by Django 3.1.5 on 2021-04-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0021_auto_20210411_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='redirect_url',
            field=models.URLField(help_text='Override default redirect (to this wall)', null=True, verbose_name='Redirect URL'),
        ),
    ]
