# Generated by Django 3.1.5 on 2021-03-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0023_auto_20210313_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='_uid',
            field=models.CharField(db_column='uid', default='notset', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='simplelist',
            name='_uid',
            field=models.CharField(db_column='uid', default='notset', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='simpletext',
            name='_uid',
            field=models.CharField(db_column='uid', default='notset', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='url',
            name='_uid',
            field=models.CharField(db_column='uid', default='notset', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wall',
            name='_uid',
            field=models.CharField(db_column='uid', default='notset', max_length=32),
            preserve_default=False,
        ),
    ]
