# Generated by Django 3.1.5 on 2021-04-25 16:45

import application.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0023_port_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Widget description'),
        ),
        migrations.AddField(
            model_name='simplelist',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Widget description'),
        ),
        migrations.AddField(
            model_name='simpleswitch',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Widget description'),
        ),
        migrations.AddField(
            model_name='simpletext',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Widget description'),
        ),
        migrations.AddField(
            model_name='url',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Widget description'),
        ),
        migrations.AlterField(
            model_name='port',
            name='redirect_url',
            field=models.URLField(blank=True, help_text='Override default redirect (to this wall)', null=True, verbose_name='Redirect URL'),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Date of last update (wall or any widget)')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Widget description')),
                ('help', models.CharField(blank=True, max_length=200, null=True)),
                ('w', models.IntegerField(default=200, validators=[django.core.validators.MinValueValidator(50)], verbose_name='Widget width')),
                ('h', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(50)], verbose_name='Widget height')),
                ('z', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Widget z index(stack position)')),
                ('x', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Offset left from parent')),
                ('y', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Offset top from parent')),
                ('font_size', models.IntegerField(default=16, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(6)], verbose_name='Widget font size')),
                ('font_weight', models.IntegerField(default=400, validators=[django.core.validators.MaxValueValidator(900), django.core.validators.MinValueValidator(100)], verbose_name='Widget font weight')),
                ('background_color', models.CharField(default='#ffffff', max_length=9, validators=[application.models.concrete.general_declaration.ColorValidator])),
                ('text_color', models.CharField(default='#000000', max_length=9, validators=[application.models.concrete.general_declaration.ColorValidator])),
                ('border', models.BooleanField(default=True)),
                ('href', models.URLField(blank=True, null=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.container')),
                ('sync_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.url')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
