# Generated by Django 3.1.5 on 2021-04-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0024_auto_20210425_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='href',
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Uploaded file'),
        ),
    ]
