# Generated by Django 3.1.5 on 2021-03-13 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0024_auto_20210313_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counter',
            name='_uid',
        ),
        migrations.RemoveField(
            model_name='simplelist',
            name='_uid',
        ),
        migrations.RemoveField(
            model_name='simpletext',
            name='_uid',
        ),
        migrations.RemoveField(
            model_name='url',
            name='_uid',
        ),
        migrations.RemoveField(
            model_name='wall',
            name='_uid',
        ),
    ]
