# Generated by Django 3.1.5 on 2021-03-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0025_auto_20210313_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='wall',
            name='allow_anonymous_view',
            field=models.BooleanField(default=False, verbose_name='Allow anonymous view mode'),
        ),
    ]
