# Generated by Django 3.1.5 on 2021-03-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0026_wall_allow_anonymous_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='wall',
            name='center_horizontally',
            field=models.BooleanField(default=False, verbose_name='Center wall horizontally'),
        ),
    ]
