# Generated by Django 3.1.5 on 2021-03-20 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0027_wall_center_horizontally'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wall',
            name='center_horizontally',
        ),
    ]
