# Generated by Django 3.1.5 on 2021-04-25 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0027_file_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
