# Generated by Django 3.1.5 on 2021-04-28 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0028_delete_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port',
            name='owner',
        ),
    ]
