# Generated by Django 3.1.5 on 2021-03-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0028_remove_wall_center_horizontally'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='h',
            field=models.IntegerField(default=150, verbose_name='Widget height'),
        ),
        migrations.AlterField(
            model_name='counter',
            name='w',
            field=models.IntegerField(default=150, verbose_name='Widget width'),
        ),
        migrations.AlterField(
            model_name='simplelist',
            name='h',
            field=models.IntegerField(default=150, verbose_name='Widget height'),
        ),
        migrations.AlterField(
            model_name='simplelist',
            name='w',
            field=models.IntegerField(default=150, verbose_name='Widget width'),
        ),
        migrations.AlterField(
            model_name='simpletext',
            name='h',
            field=models.IntegerField(default=150, verbose_name='Widget height'),
        ),
        migrations.AlterField(
            model_name='simpletext',
            name='w',
            field=models.IntegerField(default=150, verbose_name='Widget width'),
        ),
        migrations.AlterField(
            model_name='url',
            name='h',
            field=models.IntegerField(default=150, verbose_name='Widget height'),
        ),
        migrations.AlterField(
            model_name='url',
            name='w',
            field=models.IntegerField(default=150, verbose_name='Widget width'),
        ),
    ]
