# Generated by Django 3.1.5 on 2021-05-14 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0029_remove_port_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='font_size',
            field=models.IntegerField(default=14, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(6)], verbose_name='Widget font size'),
        ),
        migrations.AlterField(
            model_name='simplelist',
            name='font_size',
            field=models.IntegerField(default=14, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(6)], verbose_name='Widget font size'),
        ),
        migrations.AlterField(
            model_name='simpleswitch',
            name='font_size',
            field=models.IntegerField(default=14, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(6)], verbose_name='Widget font size'),
        ),
        migrations.AlterField(
            model_name='simpletext',
            name='font_size',
            field=models.IntegerField(default=14, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(6)], verbose_name='Widget font size'),
        ),
        migrations.AlterField(
            model_name='url',
            name='font_size',
            field=models.IntegerField(default=14, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(6)], verbose_name='Widget font size'),
        ),
    ]
