# Generated by Django 3.1.5 on 2021-03-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0029_auto_20210321_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='w',
            field=models.IntegerField(default=200, verbose_name='Widget width'),
        ),
        migrations.AlterField(
            model_name='simplelist',
            name='w',
            field=models.IntegerField(default=200, verbose_name='Widget width'),
        ),
        migrations.AlterField(
            model_name='simpletext',
            name='w',
            field=models.IntegerField(default=200, verbose_name='Widget width'),
        ),
        migrations.AlterField(
            model_name='url',
            name='w',
            field=models.IntegerField(default=200, verbose_name='Widget width'),
        ),
    ]
