# Generated by Django 3.1.5 on 2021-03-21 21:20

import application.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0030_auto_20210321_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wall',
            name='title',
            field=models.CharField(blank=True, default='Untitled', max_length=200, null=True, verbose_name='Wall title'),
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Date of last update (wall or any widget)')),
                ('w', models.IntegerField(default=200, verbose_name='Widget width')),
                ('h', models.IntegerField(default=150, verbose_name='Widget height')),
                ('z', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)], verbose_name='Widget z index(stack position)')),
                ('x', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Offset left from parent')),
                ('y', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Offset top from parent')),
                ('font_size', models.IntegerField(default=16, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(8)], verbose_name='Widget font size')),
                ('font_weight', models.IntegerField(default=400, validators=[django.core.validators.MaxValueValidator(900), django.core.validators.MinValueValidator(100)], verbose_name='Widget font weight')),
                ('background_color', models.CharField(default='#ffffff', max_length=9, validators=[application.models.ColorValidator])),
                ('text_color', models.CharField(default='#000000', max_length=9, validators=[application.models.ColorValidator])),
                ('border', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('value', models.BooleanField(default=False)),
                ('wall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.wall')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
