# Generated by Django 3.1.5 on 2021-05-26 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0030_auto_20210514_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port',
            name='wall',
        ),
        migrations.AddField(
            model_name='port',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='port',
            name='redirect_url_anonymous',
            field=models.URLField(blank=True, null=True, verbose_name='Redirect URL (anonymous)'),
        ),
        migrations.AlterField(
            model_name='port',
            name='redirect_url',
            field=models.URLField(blank=True, help_text='Override default redirect', null=True, verbose_name='Redirect URL'),
        ),
    ]
