# Generated by Django 3.1.5 on 2021-05-26 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0031_auto_20210526_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port',
            name='redirect_url',
        ),
        migrations.RemoveField(
            model_name='port',
            name='redirect_url_anonymous',
        ),
        migrations.AddField(
            model_name='port',
            name='anonymous_wall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anonymous_wall', to='application.wall'),
        ),
        migrations.AddField(
            model_name='port',
            name='authenticated_wall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authenticated_wall', to='application.wall'),
        ),
    ]
