# Generated by Django 3.1.5 on 2021-03-21 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0031_auto_20210321_2120'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Switch',
            new_name='SimpleSwitch',
        ),
    ]
