# Generated by Django 3.1.5 on 2021-03-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0032_auto_20210321_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='wall',
            name='lock_widgets',
            field=models.BooleanField(default=False, verbose_name='Lock widgets custom actions'),
        ),
    ]
