# Generated by Django 3.1.5 on 2021-06-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0032_auto_20210526_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='grid',
            field=models.BooleanField(default=False),
        ),
    ]
