# Generated by Django 3.1.5 on 2021-03-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0033_wall_lock_widgets'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='help',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='simplelist',
            name='help',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='simpleswitch',
            name='help',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='simpletext',
            name='help',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='url',
            name='help',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
