# Generated by Django 3.1.5 on 2021-03-26 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0034_auto_20210321_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wall',
            name='w',
        ),
    ]
