# Generated by Django 3.1.5 on 2021-06-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0035_remove_url_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wall',
            name='lock_widgets',
            field=models.BooleanField(default=True, verbose_name='Lock widgets at wall'),
        ),
    ]
