# Generated by Django 3.1.5 on 2021-06-14 16:32

import application.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0037_port_redirect_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Date of last update (wall or any widget)')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('wall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.wall')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Date of last update (wall or any widget)')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Widget description')),
                ('help', models.CharField(blank=True, max_length=200, null=True)),
                ('w', models.IntegerField(default=200, validators=[django.core.validators.MinValueValidator(50)], verbose_name='Widget width')),
                ('h', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(50)], verbose_name='Widget height')),
                ('z', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Widget z index(stack position)')),
                ('x', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Offset left from parent')),
                ('y', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Offset top from parent')),
                ('font_size', models.IntegerField(default=14, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(6)], verbose_name='Widget font size')),
                ('font_weight', models.IntegerField(default=400, validators=[django.core.validators.MaxValueValidator(900), django.core.validators.MinValueValidator(100)], verbose_name='Widget font weight')),
                ('background_color', models.CharField(default='#ffffff', max_length=9, validators=[application.models.ColorValidator])),
                ('text_color', models.CharField(default='#000000', max_length=9, validators=[application.models.ColorValidator])),
                ('border', models.BooleanField(default=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.container')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.source')),
                ('sync_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.document')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
