# Generated by Django 3.1.5 on 2021-06-13 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0038_content_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='sync_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.file'),
        ),
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.content'),
        ),
    ]
