# Generated by Django 3.1.5 on 2021-06-15 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0040_auto_20210614_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='source',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent', to='application.source'),
        ),
        migrations.AlterField(
            model_name='source',
            name='file',
            field=models.FileField(null=True, upload_to='%Y/%m/%d/'),
        ),
    ]
