# Generated by Django 3.1.5 on 2021-06-13 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0040_content_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='owner',
        ),
        migrations.AddField(
            model_name='content',
            name='wall',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.wall'),
            preserve_default=False,
        ),
    ]
