# Generated by Django 3.1.5 on 2021-06-16 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0041_auto_20210615_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='source',
        ),
        migrations.AddField(
            model_name='document',
            name='source',
            field=models.ManyToManyField(blank=True, null=True, related_name='parent', to='application.Source'),
        ),
    ]
