# Generated by Django 3.1.5 on 2021-06-13 19:05

from django.db import migrations, models
import django.utils.timezone
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0041_auto_20210613_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date of creation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Date of last update (wall or any widget)'),
        ),
        migrations.AlterField(
            model_name='content',
            name='id',
            field=hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False),
        ),
    ]
