# Generated by Django 3.1.5 on 2021-06-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0042_auto_20210616_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='source',
            field=models.ManyToManyField(blank=True, to='application.Source'),
        ),
    ]
