# Generated by Django 3.1.5 on 2021-06-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0042_auto_20210613_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='source',
        ),
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.FileField(null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
