# Generated by Django 3.1.5 on 2021-06-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0043_auto_20210616_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='source',
            field=models.ManyToManyField(blank=True, related_name='parent', to='application.Source'),
        ),
    ]
