# Generated by Django 3.1.5 on 2021-06-13 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0043_auto_20210613_1929'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
    ]
