# Generated by Django 3.1.5 on 2021-06-16 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0044_auto_20210616_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='source',
        ),
        migrations.AddField(
            model_name='document',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent', to='application.source'),
        ),
    ]
