# Generated by Django 3.1.5 on 2021-06-18 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0045_auto_20210616_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='counter',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='counter',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='counter',
            name='font_size',
            field=models.IntegerField(default=14, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='counter',
            name='font_weight',
            field=models.IntegerField(default=400, validators=[django.core.validators.MaxValueValidator(900), django.core.validators.MinValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='counter',
            name='h',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(50)], verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='counter',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='counter',
            name='w',
            field=models.IntegerField(default=200, validators=[django.core.validators.MinValueValidator(50)], verbose_name='Width'),
        ),
        migrations.AlterField(
            model_name='counter',
            name='x',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='counter',
            name='y',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='counter',
            name='z',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='document',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='font_size',
            field=models.IntegerField(default=14, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='document',
            name='font_weight',
            field=models.IntegerField(default=400, validators=[django.core.validators.MaxValueValidator(900), django.core.validators.MinValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='document',
            name='h',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(50)], verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='document',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='w',
            field=models.IntegerField(default=200, validators=[django.core.validators.MinValueValidator(50)], verbose_name='Width'),
        ),
        migrations.AlterField(
            model_name='document',
            name='x',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='document',
            name='y',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='document',
            name='z',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='port',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='port',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='port',
            name='visited',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='simplelist',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='simplelist',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='simplelist',
            name='font_size',
            field=models.IntegerField(default=14, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='simplelist',
            name='font_weight',
            field=models.IntegerField(default=400, validators=[django.core.validators.MaxValueValidator(900), django.core.validators.MinValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='simplelist',
            name='h',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(50)], verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='simplelist',
            name='inner_border',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='simplelist',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='simplelist',
            name='w',
            field=models.IntegerField(default=200, validators=[django.core.validators.MinValueValidator(50)], verbose_name='Width'),
        ),
        migrations.AlterField(
            model_name='simplelist',
            name='x',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='simplelist',
            name='y',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='simplelist',
            name='z',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='simpleswitch',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='simpleswitch',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='simpleswitch',
            name='font_size',
            field=models.IntegerField(default=14, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='simpleswitch',
            name='font_weight',
            field=models.IntegerField(default=400, validators=[django.core.validators.MaxValueValidator(900), django.core.validators.MinValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='simpleswitch',
            name='h',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(50)], verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='simpleswitch',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='simpleswitch',
            name='w',
            field=models.IntegerField(default=200, validators=[django.core.validators.MinValueValidator(50)], verbose_name='Width'),
        ),
        migrations.AlterField(
            model_name='simpleswitch',
            name='x',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='simpleswitch',
            name='y',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='simpleswitch',
            name='z',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='simpletext',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='simpletext',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='simpletext',
            name='font_size',
            field=models.IntegerField(default=14, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='simpletext',
            name='font_weight',
            field=models.IntegerField(default=400, validators=[django.core.validators.MaxValueValidator(900), django.core.validators.MinValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='simpletext',
            name='h',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(50)], verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='simpletext',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='simpletext',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='simpletext',
            name='w',
            field=models.IntegerField(default=200, validators=[django.core.validators.MinValueValidator(50)], verbose_name='Width'),
        ),
        migrations.AlterField(
            model_name='simpletext',
            name='x',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='simpletext',
            name='y',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='simpletext',
            name='z',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='source',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='font_size',
            field=models.IntegerField(default=14, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='url',
            name='font_weight',
            field=models.IntegerField(default=400, validators=[django.core.validators.MaxValueValidator(900), django.core.validators.MinValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='url',
            name='h',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(50)], verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='url',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='w',
            field=models.IntegerField(default=200, validators=[django.core.validators.MinValueValidator(50)], verbose_name='Width'),
        ),
        migrations.AlterField(
            model_name='url',
            name='x',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='url',
            name='y',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='url',
            name='z',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='wall',
            name='allow_anonymous_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wall',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='wall',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='wall',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='wall',
            name='lock_widgets',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='wall',
            name='title',
            field=models.CharField(blank=True, default='Untitled', max_length=200, null=True),
        ),
    ]
