# Generated by Django 3.1.5 on 2021-06-18 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0046_auto_20210618_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='h',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='container',
            name='index',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='container',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='w',
            field=models.IntegerField(default=3000),
        ),
        migrations.AlterField(
            model_name='counter',
            name='h',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='counter',
            name='w',
            field=models.IntegerField(default=200, validators=[django.core.validators.MinValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='document',
            name='h',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='document',
            name='w',
            field=models.IntegerField(default=200, validators=[django.core.validators.MinValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='simplelist',
            name='h',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='simplelist',
            name='w',
            field=models.IntegerField(default=200, validators=[django.core.validators.MinValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='simpleswitch',
            name='h',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='simpleswitch',
            name='w',
            field=models.IntegerField(default=200, validators=[django.core.validators.MinValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='simpletext',
            name='h',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='simpletext',
            name='w',
            field=models.IntegerField(default=200, validators=[django.core.validators.MinValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='url',
            name='h',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='url',
            name='w',
            field=models.IntegerField(default=200, validators=[django.core.validators.MinValueValidator(50)]),
        ),
    ]
