# Generated by Django 3.1.5 on 2021-06-26 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0047_auto_20210618_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='anonymous_wall',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anonymous_wall', to='application.wall'),
        ),
        migrations.AlterField(
            model_name='port',
            name='authenticated_wall',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authenticated_wall', to='application.wall'),
        ),
    ]
