# Generated by Django 3.1.5 on 2021-06-28 12:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0048_auto_20210626_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='wall',
            name='trusted_users',
            field=models.ManyToManyField(related_name='foreign_walls', to=settings.AUTH_USER_MODEL),
        ),
    ]
