# Generated by Django 3.1.5 on 2021-06-28 19:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0049_wall_trusted_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wall',
            name='trusted_users',
            field=models.ManyToManyField(related_name='trusted_walls', to=settings.AUTH_USER_MODEL),
        ),
    ]
