# Generated by Django 3.1.5 on 2021-06-29 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0051_auto_20210629_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter_set', to='application.container'),
        ),
        migrations.AlterField(
            model_name='document',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_set', to='application.container'),
        ),
        migrations.AlterField(
            model_name='simplelist',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simple_list_set', to='application.container'),
        ),
        migrations.AlterField(
            model_name='simpleswitch',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simple_switch_set', to='application.container'),
        ),
        migrations.AlterField(
            model_name='simpletext',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simple_text_set', to='application.container'),
        ),
        migrations.AlterField(
            model_name='url',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_set', to='application.container'),
        ),
    ]
