# Generated by Django 3.1.5 on 2021-06-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0052_auto_20210629_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='activated',
            field=models.BooleanField(default=True),
        ),
    ]
