# Generated by Django 3.1.5 on 2021-06-30 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0053_port_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.source'),
        ),
        migrations.AlterField(
            model_name='port',
            name='anonymous_wall',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anonymous_wall', to='application.wall'),
        ),
        migrations.AlterField(
            model_name='port',
            name='authenticated_wall',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authenticated_wall', to='application.wall'),
        ),
        migrations.AlterField(
            model_name='port',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='port',
            name='redirect_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
