# Generated by Django 3.1.5 on 2021-07-01 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0055_auto_20210630_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='index',
        ),
        migrations.AddField(
            model_name='container',
            name='next',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.container'),
        ),
    ]
