# Generated by Django 3.1.5 on 2021-07-01 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0056_auto_20210701_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='next',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous', to='application.container'),
        ),
    ]
