# Generated by Django 3.1.5 on 2021-07-07 11:12

import application.models.concrete.general_declaration
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0058_auto_20210706_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='visited',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('help', models.CharField(blank=True, max_length=200, null=True)),
                ('w', models.IntegerField(default=200, validators=[django.core.validators.MinValueValidator(50)])),
                ('h', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(50)])),
                ('z', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('x', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('y', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('font_size', models.IntegerField(default=14, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(6)])),
                ('font_weight', models.IntegerField(default=400, validators=[django.core.validators.MaxValueValidator(900), django.core.validators.MinValueValidator(100)])),
                ('background_color', models.CharField(default='#ffffff', max_length=9, validators=[application.models.concrete.general_declaration.ColorValidator])),
                ('text_color', models.CharField(default='#000000', max_length=9, validators=[application.models.concrete.general_declaration.ColorValidator])),
                ('border', models.BooleanField(default=True)),
                ('source', models.URLField(blank=True, null=True)),
                ('autoplay', models.BooleanField(blank=True, default=False)),
                ('loop', models.BooleanField(blank=True, default=False)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.container')),
                ('sync_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.video')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('help', models.CharField(blank=True, max_length=200, null=True)),
                ('w', models.IntegerField(default=200, validators=[django.core.validators.MinValueValidator(50)])),
                ('h', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(50)])),
                ('z', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('x', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('y', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('font_size', models.IntegerField(default=14, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(6)])),
                ('font_weight', models.IntegerField(default=400, validators=[django.core.validators.MaxValueValidator(900), django.core.validators.MinValueValidator(100)])),
                ('background_color', models.CharField(default='#ffffff', max_length=9, validators=[application.models.concrete.general_declaration.ColorValidator])),
                ('text_color', models.CharField(default='#000000', max_length=9, validators=[application.models.concrete.general_declaration.ColorValidator])),
                ('border', models.BooleanField(default=True)),
                ('source', models.URLField(blank=True, null=True)),
                ('alt', models.CharField(blank=True, default='image', max_length=200, null=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.container')),
                ('sync_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
