# Generated by Django 3.1.5 on 2021-07-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0059_auto_20210707_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='youtube',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
